version: '3'
services:
    db-quiz:
        build: ./docker/db-quiz
        container_name: "db-quiz"
        ports:
        - "3306:3306"
        environment:
        - MYSQL_ROOT_PASSWORD=xxx
        - TZ=Europe/Warsaw
        networks:
            - quiz-network
    ap-quiz:
        container_name: "ap-quiz"
        build: ./
        depends_on:
        - db-quiz
        networks:
            - quiz-network
networks:
    quiz-network:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: 172.16.240.0/24