version: '3'
services:
    db-mongo:
        image: mongo:4.2.8
        container_name: "mongodb4"
        ports:
        - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
            - MONGO_INITDB_DATABASE=codersday
        networks:
            - quiz-network
    ap-quiz:
        container_name: "ap-quiz"
        build: ./ap-quiz
        depends_on:
        - db-mongo
        networks:
            - quiz-network
networks:
    quiz-network:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: 172.16.240.0/24